# Generated by Django 4.2.9 on 2026-10-03 14:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '预览中'), ('confirmed', '已确认'), ('expired', '已失效')], default='draft', max_length=20, verbose_name='批次状态')),
                ('source', models.CharField(choices=[('manual', '人工触发计算'), ('recalc', '重新计算')], default='manual', max_length=20, verbose_name='计算来源')),
                ('available_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计算时可分配库存快照')),
                ('occupied_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='计算时已确认占用快照')),
                ('input_fingerprint', models.CharField(default='', max_length=64, verbose_name='输入数据指纹')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_allocation_batches', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allocation_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_batches', to='warehouse.goods', verbose_name='专用设备')),
            ],
            options={
                'verbose_name': '分配批次',
                'verbose_name_plural': '分配批次',
                'db_table': 'wh_allocation_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200, verbose_name='案件名称')),
                ('case_level', models.CharField(choices=[('major', '重大案件'), ('important', '重要案件'), ('normal', '一般案件')], max_length=20, verbose_name='案件等级')),
                ('apply_time', models.DateTimeField(verbose_name='申请时间')),
                ('promised_time', models.DateTimeField(verbose_name='承诺归还时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请数量')),
                ('minimum_guarantee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='最低保障量')),
                ('status', models.CharField(choices=[('draft', '待提交'), ('waiting', '等待分配'), ('allocated', '已占用'), ('returned', '已归还'), ('withdrawn', '已撤回')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_applications', to='warehouse.goods', verbose_name='专用设备')),
            ],
            options={
                'verbose_name': '专用设备申请',
                'verbose_name_plural': '专用设备申请',
                'db_table': 'wh_equipment_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='占用数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='占用开始时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='occupancy', to='warehouse.equipmentapplication', verbose_name='设备申请')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='warehouse.allocationbatch', verbose_name='确认批次')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='warehouse.goods', verbose_name='专用设备')),
            ],
            options={
                'verbose_name': '已确认占用',
                'verbose_name_plural': '已确认占用',
                'db_table': 'wh_allocation_occupancy',
            },
        ),
        migrations.CreateModel(
            name='AllocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='分配顺位')),
                ('proposed_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='建议分配量')),
                ('final_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='最终分配量')),
                ('result', models.CharField(choices=[('full', '足额满足'), ('partial', '部分满足'), ('unmet', '未满足'), ('withdrawn', '已撤回')], max_length=20, verbose_name='满足结果')),
                ('reason', models.CharField(default='', max_length=200, verbose_name='分配说明')),
                ('manual_overridden', models.BooleanField(default=False, verbose_name='是否人工调整')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_allocation_items', to=settings.AUTH_USER_MODEL, verbose_name='调整人')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_items', to='warehouse.equipmentapplication', verbose_name='设备申请')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.allocationbatch', verbose_name='分配批次')),
            ],
            options={
                'verbose_name': '分配明细',
                'verbose_name_plural': '分配明细',
                'db_table': 'wh_allocation_item',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='AllocationAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('calculate', '生成预览'), ('manual_adjust', '人工调整'), ('confirm', '确认写入'), ('withdraw', '申请撤回'), ('return', '设备归还'), ('recalc', '重新计算')], max_length=20, verbose_name='操作类型')),
                ('before_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='调整前数量')),
                ('after_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='调整后数量')),
                ('detail', models.TextField(blank=True, verbose_name='操作说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_logs', to='warehouse.equipmentapplication', verbose_name='设备申请')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='warehouse.allocationbatch', verbose_name='分配批次')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_op_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '分配操作日志',
                'verbose_name_plural': '分配操作日志',
                'db_table': 'wh_allocation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentapplication',
            index=models.Index(fields=['goods', 'status'], name='wh_equipmen_goods_i_25edad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='allocationitem',
            unique_together={('batch', 'application')},
        ),
    ]
