# Generated by Django 4.2.9 on 2026-10-03 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=100, verbose_name='案件名称')),
                ('case_level', models.CharField(choices=[('major', '重大案件'), ('important', '重要案件'), ('general', '一般案件')], default='general', max_length=20, verbose_name='案件等级')),
                ('requested_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请数量')),
                ('minimum_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='最低保障量')),
                ('committed_at', models.DateTimeField(verbose_name='承诺时间')),
                ('allocated_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已占用数量')),
                ('status', models.CharField(choices=[('pending', '待分配'), ('allocated', '已占用'), ('withdrawn', '已撤回'), ('released', '已释放')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_applications', to='warehouse.goods', verbose_name='专用设备')),
            ],
            options={
                'verbose_name': '专用设备占用申请',
                'verbose_name_plural': '专用设备占用申请',
                'db_table': 'wh_equipment_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '待确认'), ('confirmed', '已确认'), ('superseded', '已作废')], default='draft', max_length=20, verbose_name='状态')),
                ('total_available', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='生成时可用库存')),
                ('snapshot', models.JSONField(default=dict, verbose_name='生成快照')),
                ('invalid_reason', models.CharField(blank=True, max_length=200, verbose_name='作废原因')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_allocation_plans', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allocation_plans', to=settings.AUTH_USER_MODEL, verbose_name='预览生成人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_plans', to='warehouse.goods', verbose_name='专用设备')),
            ],
            options={
                'verbose_name': '设备分配方案',
                'verbose_name_plural': '设备分配方案',
                'db_table': 'wh_allocation_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='分配顺位')),
                ('requested_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请数量')),
                ('minimum_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='最低保障量')),
                ('allocated_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='分配数量')),
                ('result', models.CharField(choices=[('full', '足额分配'), ('partial', '部分满足'), ('none', '未分配')], default='none', max_length=20, verbose_name='满足结果')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='分配说明')),
                ('is_manual_adjusted', models.BooleanField(default=False, verbose_name='是否人工调整')),
                ('adjust_reason', models.CharField(blank=True, max_length=200, verbose_name='人工调整原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_allocation_items', to=settings.AUTH_USER_MODEL, verbose_name='调整人')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_items', to='warehouse.equipmentapplication', verbose_name='占用申请')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.allocationplan', verbose_name='所属方案')),
            ],
            options={
                'verbose_name': '分配方案明细',
                'verbose_name_plural': '分配方案明细',
                'db_table': 'wh_allocation_item',
                'ordering': ['rank'],
                'unique_together': {('plan', 'application')},
            },
        ),
    ]
